name: PC Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  IceSDK:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install Required Packages
        run: |
          sudo apt update
          sudo apt install -y build-essential git ccache libgl1-mesa-dev ninja-build

          git submodule update --init --recursive

      - name: Generate Build Files
        run: |
          mkdir -p ./build
          cd build && cmake .. -DICESDK_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release -G Ninja

      - name: Build IceSDK
        run: ninja -C build

      - name: Execute Tests
        run: |
          cd build/bin/ && ./TestIceSDK
  